CC=gcc

run: run.c op1.c op1.h op2.c op2.h op3.c op3.h op4.c op4.h op5.c op5.h utils_tui.c utils_tui.h
	$(CC) -o run -g run.c op1.c op1.h op2.c op2.h op3.c op3.h op4.c op4.h op5.c op5.h utils_tui.c utils_tui.h

clean: run
	rm run